var g=["UNKNOWN","ETHERNET","WIFI","CELL_2G","CELL_3G"];
function n(){this.screen={width:screen.width||-1,height:screen.height||-1,colorDepth:screen.colorDepth||0,pixelDepth:screen.pixelDepth||0};var a={};"undefined"!=typeof window.innerWidth?(a.width=window.innerWidth,a.height=window.innerHeight):"undefined"!==typeof document.documentElement&&"undefined"!==typeof document.documentElement.clientWidth&&0!==document.documentElement.clientWidth?(a.width=document.documentElement.clientWidth,a.height=document.documentElement.clientHeight):(a.width=document.getElementsByTagName("body")[0].clientWidth,
a.height=document.getElementsByTagName("body")[0].clientHeight);var e=navigator.language||"",d=navigator.browserLanguage||"",b=navigator.systemLanguage||"",c=navigator.userLanguage||"",f=navigator.platform||"",m=navigator.vendor||"",k=-1*(new Date).getTimezoneOffset()/60,l=new Date,z=(new Date).getHours(),A=a.width||-1,a=a.height||-1,i=[],h;for(o=0;o<navigator.plugins.length;o++)h=navigator.plugins[o].name.replace(/[^A-Za-z 0-9 \.,\?""!@#\$%\^&\*\(\)-_=\+;:<>\/\\\|\}\{\[\]`~]*/g,"").trim(),""!==h&&
i.push(h);var j,v;for(j=i.length;j;)for(h=--j;0<h;)if(i[j]===i[--h]){for(v=h;--h&&i[j]===i[h];);j-=i.splice(h+1,v-h).length}this.navigator={language:e,browserLanguage:d,systemLanguage:b,userLanguage:c,platform:f,vendor:m,timeZone:k,date:l,hour:z,width:A,height:a,plugins:i,flashVersion:p()};this.navigator.connectionType="undef";"undefined"!==typeof navigator.h&&g[navigator.connection.type]&&(this.navigator.connectionType=g[navigator.connection.type])}
function p(){try{try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{a.g="always"}catch(e){return"6.0.0"}}catch(d){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(b){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(c){}}return!1}
function q(){this.a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}
q.prototype.b=function(a){var e="",d,b,c,f,m,k,l=0,a=a.replace(/\r\n/g,"\n");b="";for(c=0;c<a.length;c++)f=a.charCodeAt(c),128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128));for(a=b;l<a.length;)d=a.charCodeAt(l++),b=a.charCodeAt(l++),c=a.charCodeAt(l++),f=d>>2,d=(d&3)<<4|b>>4,m=(b&15)<<2|c>>6,k=c&63,isNaN(b)?m=k=64:isNaN(c)&&(k=64),e=e+this.a.charAt(f)+this.a.charAt(d)+
this.a.charAt(m)+this.a.charAt(k);return e};"undefined"==typeof window.SC_Domain&&(window.SC_Domain="ad.smaclick.com");window.SC_SubId="undefined"==typeof window.SC_SubId?"":"&sub_id="+escape(window.SC_SubId);"undefined"==typeof window.SC_AdParams&&(window.SC_AdParams="");window.SC_CodeType="undefined"==typeof window.SC_CodeType?"&CodeType=1":"&CodeType="+window.SC_CodeType;var r="&ver=6";if("object"==typeof window._debug)for(var o in window._debug)r+="&"+o+"="+window._debug[o];
var s=navigator.cookieEnabled||"cookie"in document&&(0<document.cookie.length||-1<(document.cookie="test").indexOf.call(document.cookie,"test"));window.SC_CookieEnabled="&cookies="+(s?"1":"0");
"undefined"==typeof window.SC_CallObj&&(window.SC_CallObjObject=function(){},window.SC_CallObjObject.prototype={f:"SC_TBlock",i:function(){var a=[],e=null,e="undefined"===typeof document.getElementsByClassName?document.getElementsByTagName("div"):document.getElementsByClassName(this.f);for(o=0;o<e.length;o++)RegRes=e[o].id.match(/SC_Teaser_Block_(\d+)/i),null!==RegRes&&a.push(RegRes[1]);return a},e:function(){var a=[],e=[],d=document.referrer;try{window.opener&&window.opener.document&&(d=window.opener.document.location.toString())}catch(b){}a.RNum=
Math.floor(1E4*Math.random());a.hours=(new Date).getHours();a.Referer=escape(d.substring(0,1E3));a.unq=this.unique;a.docurl=escape(document.location.href);"undefined"!==typeof window.SC_add_params&&(a.add_params=window.SC_add_params);for(var c in a)a.hasOwnProperty(c)&&e.push(c+"="+a[c]);return e.join("&")},d:function(){var a=1;this.c("SC_unique",0)&&(a=0);this.unique=a;var e="."+document.domain.split("www.").join(""),d=new Date;d.setDate(d.getDate()+1);d.setHours(0,0,0,0);document.cookie="SC_unique="+
a+";expires="+d.toGMTString()+";path=/;domain="+e},c:function(a,e){"undefined"===typeof e&&(e=null);var d=document.cookie,b=a+"=",c=d.indexOf("; "+b);if(-1==c){if(c=d.indexOf(b),0!==c)return e}else c+=2;var f=document.cookie.indexOf(";",c);-1==f&&(f=d.length);return unescape(d.substring(c+b.length,f))}},window.SC_CallObj=new window.SC_CallObjObject);
if(window.SC_CId&&"undefined"!=window.SC_CId){var t=String(window.SC_CId).split(/_/),u=[];for(o in t)document.getElementById("SC_TBlock_"+t[o])&&u.push(t[o]);if(0===u.length)throw Error("No one div for ["+window.SC_CId+"]");var w=new n;window.SC_CallObj.d();var x=document.createElement("script");x.type="text/javascript";x.src="http://"+window.SC_Domain+"/uidsync";document.body.appendChild(x);var y="http://"+window.SC_Domain+"/adv_out?Id="+u.join("_")+window.SC_SubId+window.SC_AdParams+"&_c="+escape(document.cookie)+
window.SC_CookieEnabled+"&"+window.SC_CallObj.e()+"&client_info=",B,C=new q,D=function(){return""};"undefined"!==typeof JSON&&("undefined"!==typeof JSON.stringify?D=JSON.stringify:"undefined"!==typeof JSON.b&&(D=JSON.b));B=C.b(D(w));var E=y+B+r;window.SC_redir&&(E+="&redir=1");var F=document.createElement("script");F.type="text/javascript";F.src=E;document.body.appendChild(F)};
