# -*- coding: utf-8 -*-
"""NumIntegrals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Er41dszEZq8PlPQNGV2KVm_5ahZ3vaaS
"""

from pprint import pprint

import numpy as np
import pandas as pd
import torch
from matplotlib import pyplot as plt

plt.style.use("bmh")


def sinus_func(x) -> float:
    return np.sin(x) / (x**2 + 1)


def polynom(x):
    return 0.1 - x - x**2 - x**3 + x**4 + 0.1 * x**5


F = lambda x: (
    0.1 * x
    - 1 / 2 * x**2
    - 1 / 3 * x**3
    - 1 / 4 * x**4
    + 1 / 5 * x**5
    + 0.1 * 1 / 6 * x**6
)
I_stared = round(F(2) - F(0), 2)


class NumericalIntegration:
    num_of_plots = 0

    def __init__(self, func):
        self.function = func

    def _M_k(self, lower_limit, upper_limit, n, k=1):
        grid = torch.linspace(
            lower_limit, upper_limit, n, dtype=torch.float32, requires_grad=True
        )
        y = self.function(grid)

        grad = torch.autograd.grad(y.sum(), grid, create_graph=True)[0]

        if k == 1:
            return grad.abs().max().item()

        for order in range(2, k + 1):
            grad = torch.autograd.grad(
                grad.sum(), grid, create_graph=True if order < k else False
            )[0]

        return grad.abs().max().item()

    def rectangle(self, lower_limit, upper_limit, n, include_error_rate=False):
        step = (upper_limit - lower_limit) / n
        x_values = np.linspace(lower_limit + 0.5 * step, upper_limit - 0.5 * step, n)
        if include_error_rate:
            M_2 = self._M_k(lower_limit, upper_limit, n, k=2)
            psi = M_2 * (step**2 * (upper_limit - lower_limit))
            return np.sum(self.function(x_values)) * step, psi / 24, step
        return step, np.sum(self.function(x_values)) * step

    def trapezoidal(self, lower_limit, upper_limit, n, include_error_rate=False):
        step = (upper_limit - lower_limit) / n
        x_values = np.linspace(lower_limit, upper_limit, n + 1)
        y_values = self.function(x_values)
        integral = (step / 2) * (
            y_values[0] + 2 * np.sum(y_values[1:-1]) + y_values[-1]
        )
        if include_error_rate:
            M_2 = self._M_k(lower_limit, upper_limit, n, k=2)
            psi = M_2 * (step**2 * (upper_limit - lower_limit))
            return integral, psi / 12, step
        return step, integral

    def simpson(self, lower_limit, upper_limit, n, include_error_rate=False):
        if n % 2 != 0:
            raise ValueError("n должно быть чётным")
        step = (upper_limit - lower_limit) / n
        x_values = np.linspace(lower_limit, upper_limit, n + 1)
        y_values = self.function(x_values)
        integral = (step / 3) * (
            y_values[0]
            + 4 * np.sum(y_values[1:-1:2])
            + 2 * np.sum(y_values[2:-2:2])
            + y_values[-1]
        )

        if include_error_rate:
            M_4 = self._M_k(lower_limit, upper_limit, n, k=4)
            psi = M_4 * (step**2 * (upper_limit - lower_limit))
            return integral, psi / 2280, step
        return step, integral

    def runge_rule(self, method: str, lower_limit, upper_limit, tol=1e-5):
        n = 10
        dependense = {}

        if method == "Симпсон":
            p = 4
            current_method = self.simpson
        elif method == "Трапеции":
            p = 2
            current_method = self.trapezoidal
        elif method == "Прямоугольники":
            p = 2
            current_method = self.rectangle
        else:
            raise ValueError(f"Введенный метод {method} некорректный")
        while True:
            step, I_h = current_method(
                lower_limit=lower_limit, upper_limit=upper_limit, n=n
            )
            step, I_h2 = current_method(
                lower_limit=lower_limit, upper_limit=upper_limit, n=n * 2
            )
            error = abs(I_h2 - I_h) / (2**p - 1)
            dependense[n] = error
            n *= 2
            if abs(error / I_h2) < tol:
                return I_h2, step, error, dependense

    def plot(self, a, b, N, fontsize=16, label=""):
        NumericalIntegration.num_of_plots += 1
        X = np.linspace(a, b, N)
        Y = self.function(X)
        plt.plot(X, Y, label=label)
        plt.xlabel("x")
        plt.ylabel("f(x)")
        plt.grid(True)
        plt.legend(fontsize=fontsize)
        plt.show()


poly = NumericalIntegration(polynom)
sinus = NumericalIntegration(sinus_func)

sinus.plot(np.pi / 4, np.pi / 2, 500, label=r"$\frac{sin(x)}{x^2 + 1}$")

poly.plot(0, 2, 500, fontsize=12, label="$0.1 - x - x^2 - x^3 + x^4 + 0.1x^5$")

methods = ["Симпсон", "Трапеции", "Прямоугольники"]
results_sinus = {}
for method in methods:
    res, step, err, depen = sinus.runge_rule(
        method=method, lower_limit=np.pi / 4, upper_limit=np.pi / 2, tol=1e-8
    )
    results_sinus[method] = [res, step, err, depen]

for method in methods:
    depen_sinus = results_sinus[method][-1]
    lg_step = (list(map(lambda t: np.log10(t), depen_sinus.keys())),)
    lg_psi = (list(map(lambda t: np.log10(t), depen_sinus.values())),)
    k, _ = np.polyfit(*lg_step, *lg_psi, 1)
    print(f"порядок сходимости для {method}:{abs(k)}")
    plt.plot(*lg_step, *lg_psi, marker="o", label=method)

plt.xlabel(r"$\lg(h)$")
plt.ylabel(r"$\lg(\Psi)$")
plt.title(
    "Сходимость численных методов интегрирования по правилу Рунге"
    + "\n"
    + r"$\frac{sin(x)}{x^2 + 1}$"
)
plt.grid(True, which="both", linestyle="--")
plt.legend()
plt.tight_layout()
plt.show()

numeric_rect_error = []

numeric_trap_error = []

numeric_sim_error = []

n = np.arange(10, 1402, 2)

for n_i in n:
    I_rec, err_rec, h_rec = poly.rectangle(0, 2, n=n_i, include_error_rate=True)
    I_trap, err_trap, h_trap = poly.trapezoidal(0, 2, n=n_i, include_error_rate=True)
    I_sim, err_sim, h_sim = poly.simpson(0, 2, n=n_i, include_error_rate=True)

    numeric_rect_error.append((h_rec, abs(I_rec - I_stared)))

    numeric_trap_error.append((h_trap, abs(I_trap - I_stared)))

    numeric_sim_error.append((h_sim, abs(I_sim - I_stared)))

# --- График для метода прямоугольников ---
h_rect, phi_rect = zip(*numeric_rect_error)
h_trap, phi_trap = zip(*numeric_trap_error)
h_sim, phi_sim = zip(*numeric_sim_error)

plt.figure(figsize=(10, 6))

plt.title(
    "Сходимость методов интегрирования полинома\n$0.1 - x - x^2 - x^3 + x^4 + 0.1x^5$"
)
plt.plot(-np.log10(h_rect), np.log10(phi_rect), label="Прямоугольники")
plt.plot(-np.log10(h_trap), np.log10(phi_trap), label="Трапеции")
plt.plot(-np.log10(h_sim), np.log10(phi_sim), label="Симпсон")
plt.grid(True, which="both", linestyle="--")
plt.xlabel(r"$\lg(h)$")
plt.ylabel(r"$\lg(\Psi)$")
plt.legend()
plt.tight_layout()
plt.show()

for statistic in [numeric_rect_error, numeric_trap_error, numeric_sim_error]:
    x, y = zip(*statistic)
    k, _ = np.polyfit(-np.log10(x), np.log10(y), 1)
    if statistic == numeric_rect_error:
        print(f'Порядок сходимости для "Прямоугольник" = {abs(k)}')
    if statistic == numeric_trap_error:
        print(f'Порядок сходимости для "Трапеций" = {abs(k)}')
    if statistic == numeric_sim_error:
        print(f'Порядок сходимости для "Симпсона" = {abs(k)}')


def integral_func(x):
    inner_func = lambda t: np.cos(x + 5 * t) * np.sin(2 * x - t)
    integ = NumericalIntegration(inner_func)
    res, n, err, depen = integ.runge_rule(
        method="Симпсон", lower_limit=0, upper_limit=3, tol=1e-2
    )
    return res, n, err, depen


X = np.linspace(-2, -1, 500)
Y = [integral_func(x)[0] for x in X]

plt.figure(figsize=(8, 5))
plt.plot(X, Y, label=r"$F(x) = \int_{0}^{3} cos(x + 5t) \cdot sin(2x - t)dt$")
plt.xlabel("x")
plt.ylabel("F(x)")
plt.title("График интегральной функции F(x)")
plt.grid(True)
plt.legend()
plt.show()
